Changes for CP4D
ibm-mas/gitops pull request #136
Opened 2024-06-03 11:41 UTC by caroazad

Added changes to install cp4d

2024-06-03 11:54 UTC, whitfiea requested changes

2024-06-03 11:54 UTC, whitfiea commented on instance-applications/080-ibm-cp4d/templates/00-ibm-cp4d-prereqs.yaml
> +
What does this job do? Is it just for preparing for migrating from an older version of CP4D 4.8? If so then I don't think we need it as it is assumed that this is a new install with no previous older CP4D

2024-06-03 11:54 UTC, whitfiea commented on root-applications/ibm-mas-account-root/values.yaml
> +  revision: "mega"
need to change to poc

2024-06-03 11:54 UTC, whitfiea commented on root-applications/ibm-mas-cluster-root/values.yaml
> +  revision: "mega"
need to change to poc

2024-06-03 11:54 UTC, whitfiea commented on root-applications/ibm-mas-instance-root/values.yaml
> +  revision: "mega"
need to change to poc

2024-06-03 12:37 UTC, caroazad commented on instance-applications/080-ibm-cp4d/templates/00-ibm-cp4d-prereqs.yaml
> +
yes, i was assuming that before I saw that common services had an older version installed in noble3 so I thought it came with one of the other installs. Should we remove it?

2024-06-03 12:47 UTC, caroazad commented on instance-applications/080-ibm-cp4d/templates/00-ibm-cp4d-prereqs.yaml
> +
removed

2024-06-05 11:30 UTC, whitfiea approved these changes

2024-06-05 11:31 UTC, merged