Watson Machine Learning
ibm-mas/gitops pull request #140
Opened 2024-06-10 19:29 UTC by racree

Install WML (Watson Machine Learning) using gitops approach

2024-06-14 08:54 UTC, whitfiea requested changes

2024-06-14 08:54 UTC, whitfiea commented on instance-applications/090-ibm-wml/templates/02-ibm-wml_Subscription.yaml
> +  name: ibm-cpd-ccs-operator
Do these subscriptions clash with the other cp4d services? As these seem like generic ones (other than the cpd-wml-operator)

2024-06-17 08:38 UTC, whitfiea requested changes
Can we remove the .DS_Store file.

As well the changes mentioned the PR needs a bit more of a description of what this is adding, what is the common parts that are being added etc.

2024-06-17 08:38 UTC, whitfiea commented on instance-applications/090-ibm-wml/templates/00-ibm-wml_precheck.yaml
> +              if [[ ! -z ${IBMCPD_LOOKUP} && ${IBMCPD_LOOKUP} == *"Completed"* ]]; then
This looks like it just checks the health of the CR. in which case it would be a argo healthcheck that we need to add here https://github.com/ibm-mas/cli/blob/gitops/image/cli/mascli/templates/gitops/bootstrap/argocd.yaml#L82 and here https://github.ibm.com/automation-paas-cd-pipeline/mas-extensions

2024-06-17 08:38 UTC, whitfiea commented on instance-applications/090-ibm-wml/templates/03-ibm-wml-post-verify.yaml
> +              echo "Waiting for ccsStatus to be 'Completed'..."
Similar to the other comment that these are just healthchecks so should just be in the argo healthcheck

2024-06-17 08:38 UTC, whitfiea commented on instance-applications/090-ibm-wml/README.md
> +Deploys and configures CP4D needed for `MAS Assist` and `MAS Predict`. Deploys the CP4D platform operator and its dependencies.
readme needs updating

2024-06-17 08:38 UTC, whitfiea commented on instance-applications/090-ibm-wml/Chart.yaml
> +name: ibm-cp4d
needs updating to ibm-wml

2024-06-17 08:38 UTC, whitfiea commented on instance-applications/080-ibm-cp4d/templates/09-ibm-cp4d_services_base.yaml
> +  name: "cpd-base-sa-patch-job"
Can we add `-{{ .Values | toYaml | adler32sum }}` to the name of the job so it can be recreated if there is a change in values. the same would be for any other job we have.

2024-06-19 00:40 UTC, racree commented on instance-applications/090-ibm-wml/templates/00-ibm-wml_precheck.yaml
> +              if [[ ! -z ${IBMCPD_LOOKUP} && ${IBMCPD_LOOKUP} == *"Completed"* ]]; then
Moved check to Ibmcpd health check in mas-extensions and cli.  See PR https://github.com/ibm-mas/cli/pull/1039

2024-06-19 00:41 UTC, racree commented on instance-applications/090-ibm-wml/templates/03-ibm-wml-post-verify.yaml
> +              echo "Waiting for ccsStatus to be 'Completed'..."
Moved WmlBase check to ArogCD health check.

2024-06-19 00:41 UTC, racree commented on instance-applications/090-ibm-wml/README.md
> +Deploys and configures CP4D needed for `MAS Assist` and `MAS Predict`. Deploys the CP4D platform operator and its dependencies.
Updated README

2024-06-19 00:52 UTC, racree commented on instance-applications/080-ibm-cp4d/templates/09-ibm-cp4d_services_base.yaml
> +  name: "cpd-base-sa-patch-job"
Updated job names to include checksum

2024-06-19 06:56 UTC, whitfiea approved these changes

2024-06-19 06:56 UTC, merged