[minor] MAXMF-551
ibm-mas/gitops pull request #211
Opened 2024-10-22 17:28 UTC by chiragcsatani

MAXMF-551- Add Sanity Validation

2024-10-28 09:19 UTC, whitfiea requested changes
The tests here currently create a user in MAS and sync it to Manage. This is a good start but we need to do more tests on Manage itself to ensure that basic functionality of Manage works. We can add a comment to say that demodata is needed and then we can run various API tests on some core Manage function to make sure it is working.

2024-10-28 09:19 UTC, whitfiea commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/04-postsync-manage-sanity.yaml
> +      - ""
We don't need these on the role if we have the clusterrole

2024-10-28 09:19 UTC, whitfiea commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/04-postsync-manage-sanity.yaml
> +      - suites
Same comment as above

2024-10-28 09:19 UTC, whitfiea commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/04-postsync-manage-sanity.yaml
> +# to check for ready GPU nodes
Comment needs updating

2024-10-28 09:19 UTC, whitfiea commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/04-postsync-manage-sanity.yaml
> +        print("Created user:"+manage_user+"and Password is:"+manage_user_password)
We should remove this as it is testing MAS CORE APIs and not Manage, plus it has the password

2024-10-28 09:19 UTC, whitfiea commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/04-postsync-manage-sanity.yaml
> +    manage_user="saasuser"+str(random.randint(0,100))
Although the username has random in, we will likely start hitting the same user that was created in a previous run over time. Each run should cleanup the user so that we don't leave the users added to the system

2024-11-06 11:08 UTC, chiragcsatani commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/04-postsync-manage-sanity.yaml
> +      - ""
Rectified

2024-11-06 11:09 UTC, chiragcsatani commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/04-postsync-manage-sanity.yaml
> +      - suites
Rectified

2024-11-06 11:09 UTC, chiragcsatani commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/04-postsync-manage-sanity.yaml
> +# to check for ready GPU nodes
Rectified

2024-11-06 11:09 UTC, chiragcsatani commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/04-postsync-manage-sanity.yaml
> +        print("Created user:"+manage_user+"and Password is:"+manage_user_password)
Removed

2024-11-06 11:09 UTC, chiragcsatani commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/04-postsync-manage-sanity.yaml
> +    manage_user="saasuser"+str(random.randint(0,100))
Added Get User call, if user will be already present then will delete and then create one.

2024-11-08 16:16 UTC, whitfiea approved these changes

2024-11-08 16:17 UTC, merged