[patch] add update for cp4d 5.0.0
ibm-mas/gitops pull request #212
Opened 2024-10-24 20:50 UTC by caroazad

Add support for CP4D version 5.0.0

Issue: https://jsw.ibm.com/browse/MASCORE-3743

2024-10-29 13:52 UTC, whitfiea requested changes

2024-10-29 13:52 UTC, whitfiea commented on instance-applications/110-ibm-cp4d-operators/templates/04-ibm-cp4d_upg_cleanup.yaml
> +---
Can we add a comment to this file as to what it is doing. I assume for a clean env that this job should just complete without much work

2024-10-29 13:52 UTC, whitfiea commented on instance-applications/110-ibm-cp4d-operators/templates/04-ibm-cp4d_upg_cleanup.yaml
> +  name: "cpd-upg-cleanup-{{ .Values | toYaml | adler32sum }}"
Can we add the v1 to this name like the other jobs

2024-10-29 13:52 UTC, whitfiea commented on instance-applications/110-ibm-cp4d/templates/03-ibm-cp4d-core_ServiceAccount.yaml
> +{{- if .Values.cpd_product_version }}
is the name of this file incorrect? What is ibm-mcs?

2024-10-29 13:58 UTC, caroazad commented on instance-applications/110-ibm-cp4d/templates/03-ibm-cp4d-core_ServiceAccount.yaml
> +{{- if .Values.cpd_product_version }}
I have no idea. I have looked everywhere for ibm-mcs but that is what I saw in ansible-devops https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/roles/cp4d/tasks/main.yml#L59C1-L59C82
https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/roles/cp4d/tasks/create-cpd-core-service-accounts.yml

2024-10-29 13:59 UTC, caroazad commented on instance-applications/110-ibm-cp4d/templates/03-ibm-cp4d-core_ServiceAccount.yaml
> +{{- if .Values.cpd_product_version }}
At some point it's wcs and at another point it's mcs

2024-10-29 15:13 UTC, caroazad commented on instance-applications/110-ibm-cp4d/templates/03-ibm-cp4d-core_ServiceAccount.yaml
> +{{- if .Values.cpd_product_version }}
I found a deployment for one of the SAs ans it is ibm-mcs-

2024-10-30 09:21 UTC, whitfiea requested changes

2024-10-30 09:21 UTC, whitfiea commented on instance-applications/110-ibm-cp4d/templates/07-ibm-cp4d_patch_zenservice.yaml
>    name: "cpd-patch-zenservices-v2-{{ .Values | toYaml | adler32sum }}"
As we are changing this job but the values might not change then we need to change the v2 to a v3. This is because jobs are immutable so we have to create a new job if we want to change anything in the job.

2024-10-30 09:28 UTC, whitfiea commented
@caroazad As well as the v1 to v2 change, can we update the PR text so it provides some more info i.e. Explain what those new jobs do, say if this can be applied to a existing cp4d 4.8 deployment, and it works without changing anything else.

2024-10-31 08:51 UTC, whitfiea approved these changes

2024-10-31 08:51 UTC, merged