[minor] group sync operator
ibm-mas/gitops pull request #230
Opened 2024-11-27 10:05 UTC by boonware

2024-12-06 17:39 UTC, whitfiea requested changes

2024-12-06 17:39 UTC, whitfiea commented on cluster-applications/052-group-sync-operator/templates/04-gso_GroupSync.yaml
> +    argocd.argoproj.io/sync-wave: "052"
This would need to be in a syncwave higher than 052 as the subscription is also at 052 and on a new cluster this GroupSync kind will not be present until the subscription is complete.

2024-12-06 17:39 UTC, whitfiea commented on cluster-applications/052-group-sync-operator/README.md
> +Installs the Group Sync Operator
Is there a required level of operator needed? Might be worth adding that here

2024-12-07 20:26 UTC, whitfiea commented on cluster-applications/052-group-sync-operator/templates/04-gso_GroupSync.yaml
> +    argocd.argoproj.io/sync-wave: "052"
It would also need the annotation:     
```
argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true,Validate=false"
```
as this will allow Arg to skip a dry run that would fail if this kind is not on the cluster yet

2024-12-09 11:16 UTC, boonware commented on cluster-applications/052-group-sync-operator/README.md
> +Installs the Group Sync Operator
Comment with required version added.

2024-12-09 11:16 UTC, boonware commented on cluster-applications/052-group-sync-operator/templates/04-gso_GroupSync.yaml
> +    argocd.argoproj.io/sync-wave: "052"
Good spot, I have fixed the annotations.

2024-12-09 11:23 UTC, whitfiea approved these changes

2024-12-09 11:23 UTC, merged