Create postsync-maximoit-sanity
ibm-mas/gitops pull request #233
Opened 2024-11-27 11:25 UTC by Zaigham-abbas-rizvi

Maximo IT sanity testcases added @whitfiea

2024-11-27 11:27 UTC, Zaigham-abbas-rizvi reviewed
@whitfiea

2024-11-27 11:31 UTC, Zaigham-abbas-rizvi commented
@whitfiea please review it and approve request

2024-11-27 13:48 UTC, whitfiea requested changes
In addition to the inline comment, do we have anything that tests the deletion of these artifacts that are being created in the test? Is the fact that a random string is appended to the artifacts the way to not have clashing artifacts when the tests are run again on the same system?

Can we also have the main PR text outline what tests are being added.

2024-11-27 13:48 UTC, whitfiea commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +    def getManageComponents():
this fixture doesn't seem to be used

2024-11-27 13:48 UTC, whitfiea commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +    def getClusterInfo():
this fixture doesn't seem to be used

2024-11-27 13:48 UTC, whitfiea commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +    def updateMaxadminGroup(manage_db_connection):
this fixture doesn't seem to be used

2024-11-27 13:48 UTC, whitfiea commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +    def manage_db_connection():
this is used in the fixture below, but that fixture is not used

2024-11-27 13:48 UTC, whitfiea commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +        url = MANAGE_URL+"/oslc/apitoken/create"
I can't see where MANAGE_URL is set. There is mention in a fixture that is not used.

2024-11-27 13:48 UTC, whitfiea commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +    def fetch_system_info():
this fixture is not used

2024-11-27 13:48 UTC, whitfiea commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +        response = requests.post(f"{MANAGE_URL}api/os/cduiserviceview", json=payload, headers=HEADERS, verify=False)
Does MANAGE_URL have a / at the end?

2024-11-27 13:48 UTC, whitfiea commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +        response = requests.get(MANAGE_URL + 'api/systeminfo', headers=HEADERS, verify=False)
Connections should be verifiied. See the change in https://github.com/ibm-mas/gitops/commit/d77fde3fae89234d38c50f62b26f1d3b3215c427 on how to get the certificates in place to verify the connection. This will be for all request calls that have verify=False

2024-11-27 13:48 UTC, whitfiea commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +kind: ConfigMap
Please make the changes seen in this file in this commit https://github.com/ibm-mas/gitops/commit/62ef5ee07d19cf9d714fff50d4641cbd72429c38#diff-6dd9eac3b26112b2f13cfe95509ebadcecb495eb3d95824ab6f43e60500c940f to move the Configmap of the sanity-record to before the job, and expand the job so it runs the following code:

![image- 2024-11-27 at 13 42 15@2x](https://github.com/user-attachments/assets/eae1d7c7-fa1c-4f6f-82f5-17e0f952f2fa)

2024-11-27 13:48 UTC, whitfiea commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +    def test_ss_add_comment_on_ticket():
needs ticket_desc fixture?

2024-11-27 13:48 UTC, whitfiea commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +        return 'Incident_kwntv'
not random

2024-11-27 13:48 UTC, whitfiea commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +        return 'SERVICE_74R03'
Not random

2024-11-27 13:48 UTC, whitfiea commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +        return 'Problem_3ahd5'
Not random

2024-11-27 13:48 UTC, whitfiea commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +        return 'ServiceRequest_vjia6'
Not random

2024-11-27 13:48 UTC, whitfiea commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +        return 'BulletinBoard_ztnjv'
Not random

2024-11-28 10:57 UTC, Zaigham-abbas-rizvi commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +    def getManageComponents():
removed

2024-11-28 10:57 UTC, Zaigham-abbas-rizvi commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +    def updateMaxadminGroup(manage_db_connection):
removed

2024-11-28 10:58 UTC, Zaigham-abbas-rizvi commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +        return 'Incident_kwntv'
changes done

2024-11-28 10:58 UTC, Zaigham-abbas-rizvi commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +        return 'SERVICE_74R03'
changes done

2024-11-28 10:59 UTC, Zaigham-abbas-rizvi commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +        return 'ServiceRequest_vjia6'
changes done

2024-11-28 10:59 UTC, Zaigham-abbas-rizvi commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +        return 'BulletinBoard_ztnjv'
changes done

2024-11-28 11:00 UTC, Zaigham-abbas-rizvi commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +    def manage_db_connection():
removed

2024-11-28 11:03 UTC, Zaigham-abbas-rizvi commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +        url = MANAGE_URL+"/oslc/apitoken/create"
its is set @ line no 277


  MAS_URL=https://{masUrl.spec.host}{masUrl.spec.path}
      MAS_HOME=https://{masHome.spec.host}{masHome.spec.path}
      MAS_DOMAIN={masDomain}
      MANAGE_JDBC_URL={jdbcCfg.spec.config.url}
      MANAGE_JDBC_USERNAME={credentials.get("username")}
      MANAGE_JDBC_PASSWORD={credentials.get("password")}
      global MAS_ADMIN_USERNAME, MAS_ADMIN_PASSWORD,MANAGE_URL
      if manageUrl is not None:
          MANAGE_URL=https://{manageUrl.spec.host}{manageUrl.spec.path}maximo

2024-11-28 11:07 UTC, Zaigham-abbas-rizvi commented
> In addition to the inline comment, do we have anything that tests the deletion of these artifacts that are being created in the test? Is the fact that a random string is appended to the artifacts the way to not have clashing artifacts when the tests are run again on the same system?
> 
> Can we also have the main PR text outline what tests are being added.

it will not create issue as we are using random variable so it will not clash artifacts when the tests will run again on the same system.

2024-11-28 11:24 UTC, whitfiea commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +        url = MANAGE_URL+"/oslc/apitoken/create"
@Zaigham-abbas-rizvi I don't believe that getClusterInfo (the function/fixture) this code is in, is ever called

2024-11-28 16:09 UTC, Zaigham-abbas-rizvi commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +        url = MANAGE_URL+"/oslc/apitoken/create"
yes we are not calling getclusterinfo

2024-11-28 16:29 UTC, whitfiea commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +        url = MANAGE_URL+"/oslc/apitoken/create"
@Zaigham-abbas-rizvi so if it is not called then how does MANAGE_URL get set?

2024-12-02 06:56 UTC, Zaigham-abbas-rizvi commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +    def test_ss_add_comment_on_ticket():
Not required.

2024-12-02 06:59 UTC, Zaigham-abbas-rizvi commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +        response = requests.get(MANAGE_URL + 'api/systeminfo', headers=HEADERS, verify=False)
yes, connection should be verified we added certificates.

2024-12-02 07:00 UTC, Zaigham-abbas-rizvi commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +        response = requests.post(f"{MANAGE_URL}api/os/cduiserviceview", json=payload, headers=HEADERS, verify=False)
modified the Manage URL

2024-12-02 08:08 UTC, Zaigham-abbas-rizvi commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +kind: ConfigMap
changes done

2024-12-09 09:24 UTC, Zaigham-abbas-rizvi commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +    def test_ss_add_comment_on_ticket():
changes done

2024-12-09 09:29 UTC, Zaigham-abbas-rizvi commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +        MAS_ADMIN_PASSWORD = MAS_ADMIN_PASSWORD_BYTE.decode("utf-8")
removed this use case.

2024-12-09 09:29 UTC, Zaigham-abbas-rizvi commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +        response = requests.post(MANAGE_URL+'/maximo/api/os/CDUISRMBULLETIN?oslc.select=*&oslc', json=payload, headers=HEADERS, verify=manage_host_ca_filepath)
changes done

2024-12-09 09:31 UTC, Zaigham-abbas-rizvi commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +# -------------------------------------
uses for to get cluster secrets

2024-12-09 10:47 UTC, whitfiea requested changes

2024-12-09 10:47 UTC, whitfiea commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +{{ $job_name         :=  "postsync-sanity-manage-job" }}
Not sure why these are changed to -manage- from -maximoit-. It should be -maximoit-

2024-12-09 10:47 UTC, whitfiea commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +# -------------------------------------
the only cluster secret obtained is fo the mas core super crednetials, which are then not used. We should remove these and the code that gets the superuser and does nothing with MAS_ADMIN_PASSWORD or MAS_ADMIN_USERNAME

2024-12-09 10:47 UTC, whitfiea commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +import os
The whole of this section from line 204 to 2140 needs to be indented (with spaces) to be under tests.py

2024-12-09 10:47 UTC, whitfiea commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +    yield dyn_client
You don't need this

2024-12-09 10:47 UTC, whitfiea commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +    masapiUrl = masRouteDetails.get(name=f'{mas_instance_id}-api', namespace=masNamespace)
You don't need this

2024-12-09 10:47 UTC, whitfiea commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +    MAS_APIURL=f"https://{masapiUrl.spec.host}{masapiUrl.spec.path}"
you don't need this

2024-12-09 10:47 UTC, whitfiea commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +    MAS_ADMIN_PASSWORD = MAS_ADMIN_PASSWORD_BYTE.decode("utf-8")
you don't need this

2024-12-09 10:47 UTC, whitfiea commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +MAS_ADMIN_PASSWORD = ""
you don't need this

2024-12-09 10:47 UTC, whitfiea commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +        print("Failed to create incident:", response.status_code, response.text)
Shouldn't this fail rather than just print?
this is the same comment for all the functions below

2024-12-09 10:47 UTC, whitfiea commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +        print(f"Failed to retrieve incident: {res.status_code}, {res.text}")
This test doesn't assert anything. It can fail to create the incident but will always pass.
This is the same for TC 6,7,8,9,10,11 and 12

2024-12-09 10:47 UTC, whitfiea commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +        print("Failed to retrieve Ticket:", res.status_code, res.text)
This test doesn't assert anything. It can fail to create the incident but will always pass

2024-12-09 11:24 UTC, Zaigham-abbas-rizvi commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +{{ $job_name         :=  "postsync-sanity-manage-job" }}
changes done

2024-12-09 12:56 UTC, Zaigham-abbas-rizvi commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +        print("Failed to retrieve Ticket:", res.status_code, res.text)
added Assertion

2024-12-09 12:57 UTC, Zaigham-abbas-rizvi commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +        print(f"Failed to retrieve incident: {res.status_code}, {res.text}")
added Assertion

2024-12-09 12:58 UTC, Zaigham-abbas-rizvi commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +        print("Failed to create incident:", response.status_code, response.text)
added Assertion

2024-12-09 12:59 UTC, Zaigham-abbas-rizvi commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +MAS_ADMIN_PASSWORD = ""
removed

2024-12-09 12:59 UTC, Zaigham-abbas-rizvi commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +    masapiUrl = masRouteDetails.get(name=f'{mas_instance_id}-api', namespace=masNamespace)
removed

2024-12-09 12:59 UTC, Zaigham-abbas-rizvi commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +    yield dyn_client
removed

2024-12-09 13:00 UTC, Zaigham-abbas-rizvi commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +# -------------------------------------
removed

2024-12-09 13:51 UTC, Zaigham-abbas-rizvi commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +import os
added indentation

2024-12-09 13:52 UTC, Zaigham-abbas-rizvi commented on instance-applications/510-550-ibm-mas-suite-app-config/templates/postsync-maximoit-sanity
> +    MAS_APIURL=f"https://{masapiUrl.spec.host}{masapiUrl.spec.path}"
removed

2024-12-11 11:09 UTC, whitfiea commented
Replaced by PR #241

2024-12-11 11:09 UTC, closed without merging