[patch] Setup Db2 Backup job for Disaster recovery scenario and Compliance/SLA
ibm-mas/gitops pull request #234
Opened 2024-11-28 13:16 UTC by mnivedithaa

Issue: [MASCORE-4470](https://jsw.ibm.com/browse/MASCORE-4470)

2024-11-28 14:59 UTC, whitfiea requested changes
I think we have to guard some of these calls so that these only run when a) backup is setup i.e. there is a bucket set and b) that we allow external customers to still use this chart to setup db2 for MAS. These customers are unlikely to have ICD and I see a lot of the scripts are calling into ICD as an assumption that it will be present. We either change change scripts to do this as optional, or say this backup process is internal ibm only.

The other thing we need to check is how much of an outage that this would cause if the setup-db2 job is run again (i.e. a change in values or we have a v6 version). I see a number of db2stop calls that would mean an outage when SRE simply update the gitops version. The scripts should ideally only set when things need to be set, and only restart if it is the first time of setup.

2024-11-28 14:59 UTC, whitfiea commented on instance-applications/120-ibm-db2u-database/files/CheckCOS.sh
> +    if [ ${DB2V} = "v11.5.7.0" ]
does this mean 11.5.7.0 or below? We are installing 11.5.9.0 so it would use ` db2RemStgManager ALIAS LIST source=DB2REMOTE://AWSCOS//`. Is that expected?

2024-11-28 14:59 UTC, whitfiea commented on instance-applications/120-ibm-db2u-database/files/DB2_Backup.sh
> +	#!/bin/ksh
Not sure what is happening with the indents in this file

2024-11-28 14:59 UTC, whitfiea commented on instance-applications/120-ibm-db2u-database/templates/07-postsync-setup-db2_Job.yaml
> +  parm2: {{ .Values.db2_backup_bucket_secret_key | b64enc }}
Can we set a better name than param1 and param2?

2024-11-28 14:59 UTC, whitfiea commented on instance-applications/120-ibm-db2u-database/templates/07-postsync-setup-db2_Job.yaml
> +                      sleep 30
Would this be executed each time the job runs?

2024-12-04 11:01 UTC, mnivedithaa commented on instance-applications/120-ibm-db2u-database/files/CheckCOS.sh
> +    if [ ${DB2V} = "v11.5.7.0" ]
Yes. We will be using AWSCOS alias

2024-12-04 11:01 UTC, mnivedithaa commented on instance-applications/120-ibm-db2u-database/files/DB2_Backup.sh
> +	#!/bin/ksh
Updated the indents

2024-12-04 11:02 UTC, mnivedithaa commented on instance-applications/120-ibm-db2u-database/templates/07-postsync-setup-db2_Job.yaml
> +                      sleep 30
Made modifications in such a way that DB will be restarted only if any of the basic tablespace are created for the first time

2024-12-04 11:02 UTC, mnivedithaa commented on instance-applications/120-ibm-db2u-database/templates/07-postsync-setup-db2_Job.yaml
> +  parm2: {{ .Values.db2_backup_bucket_secret_key | b64enc }}
Updated to db2_backup_bucket_access_key and db2_backup_bucket_secret_key

2024-12-04 11:17 UTC, whitfiea requested changes

2024-12-04 11:17 UTC, whitfiea commented on instance-applications/120-ibm-db2u-database/templates/04-db2u-Backup_Cron.yaml
> +  name: "masmsbackup-managedb-{{ .Values.db2_instance_name }}-db2u-0"
Can we change the name of this as it isn't masms nor is it just managedb (could be iot/monitor) maybe: `db2-backup-job-v1-{{ .Values.db2_instance_name }}`. Then same for the container name on line 23

2024-12-04 11:17 UTC, whitfiea commented on instance-applications/120-ibm-db2u-database/templates/04-db2u-Backup_Cron.yaml
> +              image: openshift3/ose-ansible
This openshift3/ose-ansible image has not been updated since 2022. Can we use a more up to date image that is maintained? Is there anything special needed from that image or can it just run the cli image?

2024-12-04 11:17 UTC, whitfiea commented on instance-applications/120-ibm-db2u-database/templates/07-postsync-setup-db2_Job.yaml
> +                oc exec -n ${DB2_NAMESPACE} c-${DB2_INSTANCE_NAME}-db2u-0 -- su -lc "${INSTHOME}/bin/RUN_OnDemandFULL_BKP.sh | tee /tmp/runondemandfullbackup.log" db2inst1 || exit $?
We run the RUN_OnDemandFULL_BKP script here and on line 707. Is that expected to run twice? Does the full ondemand backup cause an outage?

2024-12-04 11:21 UTC, mnivedithaa commented on instance-applications/120-ibm-db2u-database/templates/07-postsync-setup-db2_Job.yaml
> +                oc exec -n ${DB2_NAMESPACE} c-${DB2_INSTANCE_NAME}-db2u-0 -- su -lc "${INSTHOME}/bin/RUN_OnDemandFULL_BKP.sh | tee /tmp/runondemandfullbackup.log" db2inst1 || exit $?
Yes. DB team wanted to take a backup after temp tablespace removal. Hence we are taking the backup twice. No it doesn't cause an outage

2024-12-04 12:25 UTC, mnivedithaa commented on instance-applications/120-ibm-db2u-database/templates/04-db2u-Backup_Cron.yaml
> +              image: openshift3/ose-ansible
updated to CLI image as only oc rsh command is used

2024-12-04 12:25 UTC, mnivedithaa commented on instance-applications/120-ibm-db2u-database/templates/04-db2u-Backup_Cron.yaml
> +  name: "masmsbackup-managedb-{{ .Values.db2_instance_name }}-db2u-0"
updated

2024-12-04 12:32 UTC, whitfiea approved these changes

2024-12-04 12:33 UTC, merged