[patch] add annotation for notification
ibm-mas/gitops pull request #44
Opened 2024-04-03 21:54 UTC by caroazad

Add annotation for slack notification on the applications

2024-04-04 10:05 UTC, whitfiea requested changes

2024-04-04 10:05 UTC, whitfiea commented on root-applications/ibm-mas-cluster-root/templates/000-ibm-operator-catalog-app.yaml
> +    notifications.argoproj.io/subscribe.on-sync-failed.slack.slack: {{ .Values.notifications.slack_channel_id }}
Can we make these optional, so that we only set these annotations if we have a value

2024-04-04 18:41 UTC, caroazad commented on root-applications/ibm-mas-cluster-root/templates/000-ibm-operator-catalog-app.yaml
> +    notifications.argoproj.io/subscribe.on-sync-failed.slack.slack: {{ .Values.notifications.slack_channel_id }}
I added a condition to all of them

2024-04-05 07:44 UTC, whitfiea approved these changes

2024-04-05 07:45 UTC, merged