[minor] [mascore-2637] support for manual_cert_mgmt: "True"
ibm-mas/gitops pull request #94
Opened 2024-05-24 11:52 UTC by padmankosalaram

2024-06-10 08:14 UTC, whitfiea requested changes

2024-06-10 08:14 UTC, whitfiea commented on cluster-applications/010-redhat-cert-manager/templates/04-postsync-update-sm_Job.yaml
> +          image: quay.io/ibmmas/cli:9.0.0-pre.gitops
It is now 9.4.0-pre.gitops

2024-06-10 08:14 UTC, whitfiea commented on instance-applications/010-ibm-sync-jobs/templates/01-ibm-mas_suite_certs_Job.yaml
> +              ansible-playbook ibm.mas_devops.run_role
Can you add a comment to say what this ansible role does and what it won't do.

2024-06-11 01:51 UTC, padmankosalaram commented on instance-applications/010-ibm-sync-jobs/templates/01-ibm-mas_suite_certs_Job.yaml
> +              ansible-playbook ibm.mas_devops.run_role
Included README of suite_certs role. 

Setting GITOPS=True will make sure, no k8s resource gets created by Ansible role. And the k8s cert resources gets created by gitops.

GITOPS feature is currently present only in `ansible-devops` repo `gitops` branch which we are using in `cli:9.4.0-pre.gitops`
https://github.com/ibm-mas/ansible-devops/blob/gitops/ibm/mas_devops/roles/suite_certs/README.md#gitops

2024-06-11 07:06 UTC, whitfiea approved these changes

2024-06-11 07:06 UTC, merged